name: Continuous Integration 
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'      
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target test --tag todo-app:test .
    - run: docker run --env-file ./.env.test todo-app:test

  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build --target production --tag funmibadev/todo-app:latest .
    - run: docker push funmibadev/todo-app:latest
    - run: curl --fail -dH -X POST ${{ secrets.AZURE_WEBHOOK_URL }}
